DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS sizes;
DROP TABLE IF EXISTS category_product_map;
DROP TABLE IF EXISTS size_product_map;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS admins;