// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: category_product_map.sql

package db

import (
	"context"
)

const addCategoryToProduct = `-- name: AddCategoryToProduct :one
INSERT INTO category_product_map (
  product_id,
  category_id
) VALUES (
  $1, $2
) RETURNING id, product_id, category_id
`

type AddCategoryToProductParams struct {
	ProductID  int32 `json:"product_id"`
	CategoryID int32 `json:"category_id"`
}

func (q *Queries) AddCategoryToProduct(ctx context.Context, arg AddCategoryToProductParams) (CategoryProductMap, error) {
	row := q.db.QueryRowContext(ctx, addCategoryToProduct, arg.ProductID, arg.CategoryID)
	var i CategoryProductMap
	err := row.Scan(&i.ID, &i.ProductID, &i.CategoryID)
	return i, err
}

const listProductsOfCategory = `-- name: ListProductsOfCategory :many
SELECT id, product_id, category_id FROM category_product_map 
WHERE category_id = $1
ORDER BY id 
LIMIT $2
OFFSET $3
`

type ListProductsOfCategoryParams struct {
	CategoryID int32 `json:"category_id"`
	Limit      int32 `json:"limit"`
	Offset     int32 `json:"offset"`
}

func (q *Queries) ListProductsOfCategory(ctx context.Context, arg ListProductsOfCategoryParams) ([]CategoryProductMap, error) {
	rows, err := q.db.QueryContext(ctx, listProductsOfCategory, arg.CategoryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CategoryProductMap{}
	for rows.Next() {
		var i CategoryProductMap
		if err := rows.Scan(&i.ID, &i.ProductID, &i.CategoryID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
