// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"time"
)

type Admin struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

type Category struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type CategoryProductMap struct {
	ID         int32 `json:"id"`
	ProductID  int32 `json:"product_id"`
	CategoryID int32 `json:"category_id"`
}

type Order struct {
	ID           int32     `json:"id"`
	Quantity     int32     `json:"quantity"`
	UserID       int32     `json:"user_id"`
	Status       int32     `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	Address      string    `json:"address"`
	ProductID    int32     `json:"product_id"`
	SelectedSize string    `json:"selected_size"`
}

type Product struct {
	ID          int32     `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	ImageUrl    string    `json:"image_url"`
	ImageID     string    `json:"image_id"`
	Price       string    `json:"price"`
}

type Size struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type SizeProductMap struct {
	ID        int32 `json:"id"`
	ProductID int32 `json:"product_id"`
	SizeID    int32 `json:"size_id"`
}

type User struct {
	ID        int32     `json:"id"`
	Email     string    `json:"email"`
	Username  string    `json:"username"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	IsAdmin   bool      `json:"is_admin"`
}
