// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"context"
)

type Querier interface {
	AddCategory(ctx context.Context, name string) (Category, error)
	AddProduct(ctx context.Context, arg AddProductParams) (Product, error)
	AddSize(ctx context.Context, name string) (Size, error)
	DeleteCategory(ctx context.Context, id int32) error
	DeleteProduct(ctx context.Context, id int32) error
	DeleteSize(ctx context.Context, id int32) error
	GetProduct(ctx context.Context, id int32) (Product, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
}

var _ Querier = (*Queries)(nil)
